<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        $productos = [
            // Herramientas Manuales (ID = 1)
            [
                'codigo' => '0031',
                'nombre' => 'Martillo de carpintero',
                'descripcion' => 'Martillo con mango de madera y cabeza de acero',
                'categoria_id' => 1,
                'precio_compra' => 20.00,
                'precio_venta' => 35.00,
                'stock' => 50,
                'stock_minimo' => 10,
                'proveedor_id' => 1,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.P3bxqtSAsRafwKhElyU7EAHaGW?w=217&h=186&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '002',
                'nombre' => 'Destornillador plano',
                'descripcion' => 'Destornillador de punta plana, mango ergonómico',
                'categoria_id' => 1,
                'precio_compra' => 5.00,
                'precio_venta' => 8.50,
                'stock' => 100,
                'stock_minimo' => 15,
                'proveedor_id' => 1,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.DUw2-a8uHayFrSN4n9JDIQAAAA?w=187&h=187&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3r',
            ],
            [
                'codigo' => '003',
                'nombre' => 'Llave ajustable',
                'descripcion' => 'Llave inglesa de acero, 12 pulgadas',
                'categoria_id' => 1,
                'precio_compra' => 18.00,
                'precio_venta' => 28.00,
                'stock' => 40,
                'stock_minimo' => 5,
                'proveedor_id' => 1,
                'imagen_url' => 'https://th.bing.com/th/id/R.da55af6ceb519b74494065c77f754617?rik=bJFb4C3cMZcY9g&pid=ImgRaw&r=0',
            ],

            // Electricidad (ID = 2)
            [
                'codigo' => '004',
                'nombre' => 'Cable eléctrico 2x1.5mm',
                'descripcion' => 'Cable doble recubierto, 50m',
                'categoria_id' => 2,
                'precio_compra' => 60.00,
                'precio_venta' => 90.00,
                'stock' => 20,
                'stock_minimo' => 5,
                'proveedor_id' => 1,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.y0O66jHniQ5F0vdhlgPfbgHaD5?w=290&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '005',
                'nombre' => 'Interruptor doble',
                'descripcion' => 'Interruptor de luz blanco, 10A',
                'categoria_id' => 2,
                'precio_compra' => 3.00,
                'precio_venta' => 5.00,
                'stock' => 80,
                'stock_minimo' => 10,
                'proveedor_id' => 1,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.nXYYIwyKQjXQsUhuZP43gAHaHa?w=195&h=195&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '006',
                'nombre' => 'Foco LED 10W',
                'descripcion' => 'Foco de luz blanca, bajo consumo',
                'categoria_id' => 2,
                'precio_compra' => 2.50,
                'precio_venta' => 4.00,
                'stock' => 100,
                'stock_minimo' => 20,
                'proveedor_id' => 1,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.wt10QhuBnoSuilUegRAYrgHaHa?w=216&h=216&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],

            // Fontanería (ID = 3)
            [
                'codigo' => '007',
                'nombre' => 'Grifo de cocina',
                'descripcion' => 'Grifo metálico cromado de doble salida',
                'categoria_id' => 3,
                'precio_compra' => 25.00,
                'precio_venta' => 42.00,
                'stock' => 15,
                'stock_minimo' => 5,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.sLEZPRPX7VxvjNPlvbVZFwHaIL?w=183&h=202&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '008',
                'nombre' => 'Tubería PVC 1"',
                'descripcion' => 'Tubo de PVC de 3 metros',
                'categoria_id' => 3,
                'precio_compra' => 7.00,
                'precio_venta' => 12.00,
                'stock' => 60,
                'stock_minimo' => 10,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.48_D5SUwgVe41j7vfMWszwHaHa?w=192&h=192&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '009',
                'nombre' => 'Codo PVC 90°',
                'descripcion' => 'Conector angular para tubería de 1"',
                'categoria_id' => 3,
                'precio_compra' => 1.50,
                'precio_venta' => 3.00,
                'stock' => 100,
                'stock_minimo' => 20,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.LuLcqMfYw_Wb7n-aitYrTwHaHa?w=209&h=209&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],

            // Construcción (ID = 4)
            [
                'codigo' => '010',
                'nombre' => 'Bolsa de cemento 50kg',
                'descripcion' => 'Cemento Portland para construcción general',
                'categoria_id' => 4,
                'precio_compra' => 45.00,
                'precio_venta' => 70.00,
                'stock' => 25,
                'stock_minimo' => 10,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.0ak0tsLBwsdt6CZ0uDOLCAHaD4?w=333&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '011',
                'nombre' => 'Ladrillo hueco',
                'descripcion' => 'Ladrillo para muros, 30x15x10 cm',
                'categoria_id' => 4,
                'precio_compra' => 0.60,
                'precio_venta' => 1.00,
                'stock' => 500,
                'stock_minimo' => 100,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.3H1qV8jV-7sO2K3pFrlGzAHaF7?w=197&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '012',
                'nombre' => 'Pala de construcción',
                'descripcion' => 'Pala metálica con mango de madera',
                'categoria_id' => 4,
                'precio_compra' => 18.00,
                'precio_venta' => 30.00,
                'stock' => 30,
                'stock_minimo' => 5,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.n9_LUm85v02iK7daUIxluQHaHa?w=185&h=185&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],

            // Pinturas y Acabados (ID = 5)
            [
                'codigo' => '013',
                'nombre' => 'Pintura blanca 1 galón',
                'descripcion' => 'Pintura latex para interiores',
                'categoria_id' => 5,
                'precio_compra' => 35.00,
                'precio_venta' => 55.00,
                'stock' => 20,
                'stock_minimo' => 5,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.bfdJnLlS_Vi4BppWtLeW1wHaHa?w=216&h=216&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '014',
                'nombre' => 'Rodillo de pintura',
                'descripcion' => 'Rodillo de espuma con mango ergonómico',
                'categoria_id' => 5,
                'precio_compra' => 6.00,
                'precio_venta' => 9.50,
                'stock' => 40,
                'stock_minimo' => 10,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.WG7oaX3_JnY_OoiztN2puwHaE7?w=296&h=197&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '015',
                'nombre' => 'Brocha 2"',
                'descripcion' => 'Brocha de cerdas sintéticas',
                'categoria_id' => 5,
                'precio_compra' => 3.00,
                'precio_venta' => 5.00,
                'stock' => 60,
                'stock_minimo' => 10,
                'proveedor_id' => 2,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.rAxpwciG9Mq71VIh8RtP-QHaHa?w=184&h=184&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],

            // Seguridad Industrial (ID = 6)
            [
                'codigo' => '016',
                'nombre' => 'Casco de seguridad',
                'descripcion' => 'Casco con ajuste y visera',
                'categoria_id' => 6,
                'precio_compra' => 15.00,
                'precio_venta' => 25.00,
                'stock' => 35,
                'stock_minimo' => 5,
                'proveedor_id' => 3,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.2Npd8y58XmOrVrrfu9UqnwHaGB?w=255&h=207&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '017',
                'nombre' => 'Guantes de cuero',
                'descripcion' => 'Guantes de protección industrial',
                'categoria_id' => 6,
                'precio_compra' => 12.00,
                'precio_venta' => 18.00,
                'stock' => 50,
                'stock_minimo' => 10,
                'proveedor_id' => 3,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.QYZ995tTbd-j6Pr3OxzTJwHaHu?w=204&h=213&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '018',
                'nombre' => 'Lentes de seguridad',
                'descripcion' => 'Gafas protectoras con protección UV',
                'categoria_id' => 6,
                'precio_compra' => 8.00,
                'precio_venta' => 12.00,
                'stock' => 60,
                'stock_minimo' => 15,
                'proveedor_id' => 3,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.aw6eksUIa4y_9pqutTgnXQHaHa?w=199&h=199&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],

            // Ferretería General (ID = 7)
            [
                'codigo' => '019',
                'nombre' => 'Clavos 2"',
                'descripcion' => 'Caja de clavos de 2 pulgadas',
                'categoria_id' => 7,
                'precio_compra' => 5.00,
                'precio_venta' => 8.00,
                'stock' => 80,
                'stock_minimo' => 20,
                'proveedor_id' => 3,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.9hszRTYeU3JngzCgJeWNbgHaFA?w=297&h=201&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '020',
                'nombre' => 'Tornillos Philips',
                'descripcion' => 'Tornillos cabeza Philips 3cm',
                'categoria_id' => 7,
                'precio_compra' => 6.00,
                'precio_venta' => 9.00,
                'stock' => 100,
                'stock_minimo' => 25,
                'proveedor_id' => 3,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.yj6RjDVYWddHkTUrLRXHqwHaFh?w=267&h=199&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
            [
                'codigo' => '021',
                'nombre' => 'Bisagra metálica',
                'descripcion' => 'Bisagra para puertas de madera',
                'categoria_id' => 7,
                'precio_compra' => 2.00,
                'precio_venta' => 3.50,
                'stock' => 70,
                'stock_minimo' => 10,
                'proveedor_id' => 3,
                'imagen_url' => 'https://th.bing.com/th/id/OIP.cWHKRH6xpHOw5fLXVjIRfQHaD9?w=311&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
            ],
        ];

        foreach ($productos as $producto) {
            Producto::create($producto);
        }
    }
}
